[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
  publish = "public" 
  command = "CI= yarn build" 

[[redirects]]
  from = "/data/images/ticket/*" 
  to = "/data/images/ticket/:splat"
  status = 200 
  force = false 